# Generated by Django 5.1.15 on 2026-06-27 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='Komentar'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent', verbose_name='Konten'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemember', verbose_name='Pengguna'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='-', verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Gambar'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='Default Course', max_length=100, verbose_name='Nama Mata Kuliah'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=10000, verbose_name='Harga'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Pengajar'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.course', verbose_name='Mata Kuliah'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(default='-', verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Judul Course'),
        ),
        migrations.AlterField(
            model_name='coursecontentcompletion',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursecontent', verbose_name='Konten'),
        ),
        migrations.AlterField(
            model_name='coursecontentcompletion',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemember', verbose_name='Anggota Kelas'),
        ),
    ]
