# Generated by Django 5.1.15 on 2026-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
    ]
